name: PR Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true # main will do a clean run; deployment is still done manually see https://github.com/actions/setup-dotnet?tab=readme-ov-file#caching-nuget-packages if NU1403 error appears
      - name: Test
        if: matrix.os != 'ubuntu-latest'
        run: dotnet test
      # cover only one platform for now since it would produce too many comments on the PR otherwise
      - name: Coverage
        if: matrix.os == 'ubuntu-latest'
        continue-on-error: true # we want to publish results of failed tests
        run: dotnet test --collect:"XPlat Code Coverage"
      - name: Combine Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@v5.4.5 # https://github.com/danielpalme/ReportGenerator-GitHub-Action/blob/main/action.yml
        if: matrix.os == 'ubuntu-latest'
        with:
          reports: "**/*.cobertura.xml"
          targetdir: "."
          reporttypes: "Cobertura"
          verbosity: "Info"
          title: "Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          toolpath: "reportgeneratortool"

      - name: Publish Code Coverage Report # https://github.com/irongut/CodeCoverageSummary/blob/master/action.yml last commit: 2022-10-19
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: matrix.os == 'ubuntu-latest'
        with:
          filename: "**/Cobertura.xml"
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "10 30"

      - name: Add Coverage PR Comment # https://github.com/marocchino/sticky-pull-request-comment/blob/main/action.yml
        uses: marocchino/sticky-pull-request-comment@v2.9.2
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md