name: Build main
on:
  push:
    branches:
      - main


jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Test
        run: dotnet test --configuration Release
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # we just need the latest tag reachable from head
          fetch-tags: true
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build # for test purposes; releases are still manual
        shell: pwsh
        run: |
          $version = git tag | where {$_ -imatch "v\d+\.\d+\.\d+"} | sort | select -Last 1 |% {$_.Substring(1)}
          if ($version -eq $null) {
            $version = "versionNotFound"
          }
          ./build.ps1 -version $version
          echo "TAG=$version" >> $env:GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build_${{ env.TAG }}_${{ github.run_id }}_${{ github.run_number }}
          path: uploads/*