name: PR Build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore /p:EnableWindowsTargeting=true
      - name: Test
        continue-on-error: true
        run: dotnet test -c Debug --logger trx --collect:"XPlat Code Coverage"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.17.1
        with:
          # NOTE: using trx_files instead of files due to https://github.com/EnricoMi/publish-unit-test-result-action/issues/424
          trx_files: "**/*.trx"