name: PR Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  ARTIFACT_FOLDER: artifacts

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Test
        run: dotnet test --logger:trx
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}_artifacts
          path: |
            **/*.trx
  publish_test_results:
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.ARTIFACT_FOLDER }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ${{ env.ARTIFACT_FOLDER }}/**/*.trx