name: PR Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Set PowerShell execution policy # for smb shares
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell
        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser -Force
      - name: Test
        run: dotnet test