name: Build main
on:
  push:
    branches:
      - main


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
      - name: Test
        run: dotnet test --configuration Release
      - name: Pack
        run: dotnet pack --no-restore --configuration Release